/* oxlint-disable */

export type { VoloAbpApplicationDtosPagedResultDto1VoloAbpTenantManagementTenantDtoVoloAbpTenantManagementApplicationContractsVersion10500CultureneutralPublicKeyTokennull } from "./abp/tenantManagement/application/ContractsVersion10500CultureneutralPublicKeyTokennull.ts";
