/* oxlint-disable */

export type { VoloAbpApplicationDtosPagedResultDto1VoloAbpTenantManagementTenantDtoVoloAbpTenantManagementApplicationContractsVersion10600CultureneutralPublicKeyTokennull } from "./abp/tenantManagement/application/ContractsVersion10600CultureneutralPublicKeyTokennull.ts";
