/* oxlint-disable */

export type { VoloAbpApplicationDtosPagedResultDto1VoloAbpTenantManagementTenantDtoVoloAbpTenantManagementApplicationContractsVersion10400CultureneutralPublicKeyTokennull } from "./abp/tenantManagement/application/ContractsVersion10400CultureneutralPublicKeyTokennull.ts";
