/**
 * SaaS Editions API client.
 *
 * The open-source ABP <c>Volo.Abp.TenantManagement</c> module ships no Edition
 * entity or HTTP API; the backend exposes a custom <c>EditionAppService</c>
 * (CRUD) auto-routed by ABP at <c>/api/app/edition</c>.
 *
 * Unlike <c>src/api/</c> (auto-generated by Kubb from Swagger), this module is
 * hand-written because the Editions feature is a project-specific custom
 * service that mirrors ABP Commercial SaaS Pro. It uses the shared axios
 * instance from <c>@kubb/plugin-client/clients/axios</c> so the existing
 * auth/tenant/locale interceptors apply automatically.
 */
import client from "@kubb/plugin-client/clients/axios";
import type { RequestConfig } from "@kubb/plugin-client/clients/axios";
import { queryOptions, useMutation, useQuery } from "@tanstack/react-query";
import { useQueryClient } from "@tanstack/react-query";

// ── Types ───────────────────────────────────────────────────────────

export interface EditionDto {
  id?: string;
  displayName?: string | null;
  creationTime?: string;
  creatorId?: string | null;
  lastModificationTime?: string | null;
  lastModifierId?: string | null;
  isDeleted?: boolean;
  deleterId?: string | null;
  deletionTime?: string | null;
}

export interface CreateUpdateEditionDto {
  displayName: string;
}

export interface EditionGetListInput {
  Filter?: string;
  Sorting?: string;
  SkipCount?: number;
  MaxResultCount?: number;
}

interface PagedResultDto<T> {
  items?: T[] | null;
  totalCount?: number;
}

// ── URL ─────────────────────────────────────────────────────────────

const EDITIONS_URL = "/api/app/edition";
const editionUrl = (id: string) => `${EDITIONS_URL}/${id}`;

// ── Raw API functions ───────────────────────────────────────────────

async function editionGetList(
  params?: EditionGetListInput,
  config: Partial<RequestConfig> = {},
): Promise<PagedResultDto<EditionDto>> {
  const res = await client<PagedResultDto<EditionDto>>({
    method: "GET",
    url: EDITIONS_URL,
    params,
    ...config,
  });
  return res.data;
}

async function editionGet(id: string, config: Partial<RequestConfig> = {}): Promise<EditionDto> {
  const res = await client<EditionDto>({
    method: "GET",
    url: editionUrl(id),
    ...config,
  });
  return res.data;
}

async function editionCreate(
  data: CreateUpdateEditionDto,
  config: Partial<RequestConfig> = {},
): Promise<EditionDto> {
  const res = await client<EditionDto>({
    method: "POST",
    url: EDITIONS_URL,
    data,
    ...config,
  });
  return res.data;
}

async function editionUpdate(
  id: string,
  data: CreateUpdateEditionDto,
  config: Partial<RequestConfig> = {},
): Promise<EditionDto> {
  const res = await client<EditionDto>({
    method: "PUT",
    url: editionUrl(id),
    data,
    ...config,
  });
  return res.data;
}

async function editionDelete(id: string, config: Partial<RequestConfig> = {}): Promise<void> {
  await client<void>({
    method: "DELETE",
    url: editionUrl(id),
    ...config,
  });
}

// ── Query keys ──────────────────────────────────────────────────────

export const editionGetListQueryKey = (params?: EditionGetListInput) =>
  [{ url: EDITIONS_URL }, ...(params ? [params] : [])] as const;

export const editionGetQueryKey = (id: string) => [{ url: editionUrl(id) }] as const;

// ── Query options (compatible with useDataTableQuery) ───────────────

export function editionGetListQueryOptions(
  params?: EditionGetListInput,
  config: Partial<RequestConfig> = {},
) {
  const queryKey = editionGetListQueryKey(params);
  return queryOptions({
    queryKey,
    queryFn: async ({ signal }) =>
      editionGetList(params, { ...config, signal: config.signal ?? signal }),
  });
}

export function editionGetQueryOptions(id: string, config: Partial<RequestConfig> = {}) {
  const queryKey = editionGetQueryKey(id);
  return queryOptions({
    queryKey,
    queryFn: async ({ signal }) => editionGet(id, { ...config, signal: config.signal ?? signal }),
  });
}

// ── Mutation hooks ──────────────────────────────────────────────────

export function useEditionCreate() {
  const queryClient = useQueryClient();
  return useMutation({
    mutationFn: (data: CreateUpdateEditionDto) => editionCreate(data),
    onSuccess: () => {
      void queryClient.invalidateQueries({ queryKey: [{ url: EDITIONS_URL }] });
    },
  });
}

export function useEditionUpdate() {
  const queryClient = useQueryClient();
  return useMutation({
    mutationFn: ({ id, data }: { id: string; data: CreateUpdateEditionDto }) =>
      editionUpdate(id, data),
    onSuccess: () => {
      void queryClient.invalidateQueries({ queryKey: [{ url: EDITIONS_URL }] });
    },
  });
}

export function useEditionDelete() {
  const queryClient = useQueryClient();
  return useMutation({
    mutationFn: (id: string) => editionDelete(id),
    onSuccess: () => {
      void queryClient.invalidateQueries({ queryKey: [{ url: EDITIONS_URL }] });
    },
  });
}

// Re-export useQuery for callers that want direct access.
export { useQuery };
