/* oxlint-disable */

export type {
  MediaDescriptorDownloadPathId,
  MediaDescriptorDownloadRequestConfig,
  MediaDescriptorDownloadResponse,
  MediaDescriptorDownloadResponses,
  MediaDescriptorDownloadStatus200,
  MediaDescriptorDownloadStatus200Json,
  MediaDescriptorDownloadStatus200Json2,
  MediaDescriptorDownloadStatus200Plain,
  MediaDescriptorDownloadStatus400,
  MediaDescriptorDownloadStatus400Json,
  MediaDescriptorDownloadStatus400Json2,
  MediaDescriptorDownloadStatus400Plain,
  MediaDescriptorDownloadStatus401,
  MediaDescriptorDownloadStatus401Json,
  MediaDescriptorDownloadStatus401Json2,
  MediaDescriptorDownloadStatus401Plain,
  MediaDescriptorDownloadStatus403,
  MediaDescriptorDownloadStatus403Json,
  MediaDescriptorDownloadStatus403Json2,
  MediaDescriptorDownloadStatus403Plain,
  MediaDescriptorDownloadStatus404,
  MediaDescriptorDownloadStatus404Json,
  MediaDescriptorDownloadStatus404Json2,
  MediaDescriptorDownloadStatus404Plain,
  MediaDescriptorDownloadStatus500,
  MediaDescriptorDownloadStatus500Json,
  MediaDescriptorDownloadStatus500Json2,
  MediaDescriptorDownloadStatus500Plain,
  MediaDescriptorDownloadStatus501,
  MediaDescriptorDownloadStatus501Json,
  MediaDescriptorDownloadStatus501Json2,
  MediaDescriptorDownloadStatus501Plain,
} from "./MediaDescriptorDownload.ts";
