/* oxlint-disable */

export type { VoloAbpApplicationDtosPagedResultDto1VoloAbpTenantManagementTenantDtoVoloAbpTenantManagementApplicationContractsVersion10500CultureneutralPublicKeyTokennull } from "./application/ContractsVersion10500CultureneutralPublicKeyTokennull.ts";
