allowBuilds:
  es5-ext: set this to true or false
catalog:
  vite: npm:@voidzero-dev/vite-plus-core@latest
  vitest: 4.1.9
  vite-plus: ^0.2.9
minimumReleaseAgeExclude:
  - "@kubb/plugin-axios@5.0.0"
  - "@kubb/plugin-react-query@5.0.0"
  - "@kubb/plugin-ts@5.0.0"
  - "@kubb/plugin-zod@5.0.0"
overrides:
  vite: "catalog:"
  vitest: "catalog:"
peerDependencyRules:
  allowAny:
    - vite
    - vitest
  allowedVersions:
    vite: "*"
    vitest: "*"
