/* oxlint-disable */

export type {
  TagGetListQueryFilter,
  TagGetListQueryMaxResultCount,
  TagGetListQuerySkipCount,
  TagGetListQuerySorting,
  TagGetListRequestConfig,
  TagGetListResponse,
  TagGetListResponses,
  TagGetListStatus200,
  TagGetListStatus200Json,
  TagGetListStatus200Json2,
  TagGetListStatus200Plain,
  TagGetListStatus400,
  TagGetListStatus400Json,
  TagGetListStatus400Json2,
  TagGetListStatus400Plain,
  TagGetListStatus401,
  TagGetListStatus401Json,
  TagGetListStatus401Json2,
  TagGetListStatus401Plain,
  TagGetListStatus403,
  TagGetListStatus403Json,
  TagGetListStatus403Json2,
  TagGetListStatus403Plain,
  TagGetListStatus404,
  TagGetListStatus404Json,
  TagGetListStatus404Json2,
  TagGetListStatus404Plain,
  TagGetListStatus500,
  TagGetListStatus500Json,
  TagGetListStatus500Json2,
  TagGetListStatus500Plain,
  TagGetListStatus501,
  TagGetListStatus501Json,
  TagGetListStatus501Json2,
  TagGetListStatus501Plain,
} from "./TagGetList.ts";
