/* oxlint-disable */

export type { VoloAbpApplicationDtosListResultDto1VoloCmsKitMenusMenuItemDtoVoloCmsKitCommonApplicationContractsVersion10600CultureneutralPublicKeyTokennull } from "./cmsKit/common/application/ContractsVersion10600CultureneutralPublicKeyTokennull.ts";
