/* oxlint-disable */

export type { VoloAbpApplicationDtosListResultDto1VoloAbpIdentityIdentityRoleDtoVoloAbpIdentityApplicationContractsVersion10500CultureneutralPublicKeyTokennull } from "./identity/application/ContractsVersion10500CultureneutralPublicKeyTokennull.ts";
