/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as R403RouteImport } from './routes/403'
import { Route as AccountRouteRouteImport } from './routes/account/route'
import { Route as AuditLogsRouteImport } from './routes/audit-logs'
import { Route as BackgroundJobsRouteImport } from './routes/background-jobs'
import { Route as BooksRouteImport } from './routes/books'
import { Route as FeaturesRouteImport } from './routes/features'
import { Route as GdprRouteImport } from './routes/gdpr'
import { Route as IdentityRouteRouteImport } from './routes/identity/route'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as TenantsRouteImport } from './routes/tenants'
import { Route as AccountIndexRouteImport } from './routes/account/index'
import { Route as AccountForgotPasswordRouteImport } from './routes/account/forgot-password'
import { Route as AccountLoginRouteImport } from './routes/account/login'
import { Route as AccountRegisterRouteImport } from './routes/account/register'
import { Route as AccountResetPasswordRouteImport } from './routes/account/reset-password'
import { Route as FileManagementIndexRouteImport } from './routes/file-management/index'
import { Route as IdentityIndexRouteImport } from './routes/identity/index'
import { Route as IdentityPermissionsRouteImport } from './routes/identity/permissions'
import { Route as IdentityRolesRouteImport } from './routes/identity/roles'
import { Route as IdentityUsersRouteImport } from './routes/identity/users'
import { Route as OpeniddictApplicationsRouteImport } from './routes/openiddict/applications'
import { Route as OpeniddictScopesRouteImport } from './routes/openiddict/scopes'
import { Route as SaasEditionsRouteImport } from './routes/saas/editions'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const R403Route = R403RouteImport.update({
  id: '/403',
  path: '/403',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRouteRoute = AccountRouteRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditLogsRoute = AuditLogsRouteImport.update({
  id: '/audit-logs',
  path: '/audit-logs',
  getParentRoute: () => rootRouteImport,
} as any)
const BackgroundJobsRoute = BackgroundJobsRouteImport.update({
  id: '/background-jobs',
  path: '/background-jobs',
  getParentRoute: () => rootRouteImport,
} as any)
const BooksRoute = BooksRouteImport.update({
  id: '/books',
  path: '/books',
  getParentRoute: () => rootRouteImport,
} as any)
const FeaturesRoute = FeaturesRouteImport.update({
  id: '/features',
  path: '/features',
  getParentRoute: () => rootRouteImport,
} as any)
const GdprRoute = GdprRouteImport.update({
  id: '/gdpr',
  path: '/gdpr',
  getParentRoute: () => rootRouteImport,
} as any)
const IdentityRouteRoute = IdentityRouteRouteImport.update({
  id: '/identity',
  path: '/identity',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const TenantsRoute = TenantsRouteImport.update({
  id: '/tenants',
  path: '/tenants',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountIndexRoute = AccountIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AccountRouteRoute,
} as any)
const AccountForgotPasswordRoute = AccountForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => AccountRouteRoute,
} as any)
const AccountLoginRoute = AccountLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AccountRouteRoute,
} as any)
const AccountRegisterRoute = AccountRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => AccountRouteRoute,
} as any)
const AccountResetPasswordRoute = AccountResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => AccountRouteRoute,
} as any)
const FileManagementIndexRoute = FileManagementIndexRouteImport.update({
  id: '/file-management/',
  path: '/file-management/',
  getParentRoute: () => rootRouteImport,
} as any)
const IdentityIndexRoute = IdentityIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => IdentityRouteRoute,
} as any)
const IdentityPermissionsRoute = IdentityPermissionsRouteImport.update({
  id: '/permissions',
  path: '/permissions',
  getParentRoute: () => IdentityRouteRoute,
} as any)
const IdentityRolesRoute = IdentityRolesRouteImport.update({
  id: '/roles',
  path: '/roles',
  getParentRoute: () => IdentityRouteRoute,
} as any)
const IdentityUsersRoute = IdentityUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => IdentityRouteRoute,
} as any)
const OpeniddictApplicationsRoute = OpeniddictApplicationsRouteImport.update({
  id: '/openiddict/applications',
  path: '/openiddict/applications',
  getParentRoute: () => rootRouteImport,
} as any)
const OpeniddictScopesRoute = OpeniddictScopesRouteImport.update({
  id: '/openiddict/scopes',
  path: '/openiddict/scopes',
  getParentRoute: () => rootRouteImport,
} as any)
const SaasEditionsRoute = SaasEditionsRouteImport.update({
  id: '/saas/editions',
  path: '/saas/editions',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account': typeof AccountRouteRouteWithChildren
  '/identity': typeof IdentityRouteRouteWithChildren
  '/403': typeof R403Route
  '/audit-logs': typeof AuditLogsRoute
  '/background-jobs': typeof BackgroundJobsRoute
  '/books': typeof BooksRoute
  '/features': typeof FeaturesRoute
  '/gdpr': typeof GdprRoute
  '/profile': typeof ProfileRoute
  '/settings': typeof SettingsRoute
  '/tenants': typeof TenantsRoute
  '/account/forgot-password': typeof AccountForgotPasswordRoute
  '/account/login': typeof AccountLoginRoute
  '/account/register': typeof AccountRegisterRoute
  '/account/reset-password': typeof AccountResetPasswordRoute
  '/identity/permissions': typeof IdentityPermissionsRoute
  '/identity/roles': typeof IdentityRolesRoute
  '/identity/users': typeof IdentityUsersRoute
  '/openiddict/applications': typeof OpeniddictApplicationsRoute
  '/openiddict/scopes': typeof OpeniddictScopesRoute
  '/saas/editions': typeof SaasEditionsRoute
  '/account/': typeof AccountIndexRoute
  '/file-management/': typeof FileManagementIndexRoute
  '/identity/': typeof IdentityIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/403': typeof R403Route
  '/audit-logs': typeof AuditLogsRoute
  '/background-jobs': typeof BackgroundJobsRoute
  '/books': typeof BooksRoute
  '/features': typeof FeaturesRoute
  '/gdpr': typeof GdprRoute
  '/profile': typeof ProfileRoute
  '/settings': typeof SettingsRoute
  '/tenants': typeof TenantsRoute
  '/account/forgot-password': typeof AccountForgotPasswordRoute
  '/account/login': typeof AccountLoginRoute
  '/account/register': typeof AccountRegisterRoute
  '/account/reset-password': typeof AccountResetPasswordRoute
  '/identity/permissions': typeof IdentityPermissionsRoute
  '/identity/roles': typeof IdentityRolesRoute
  '/identity/users': typeof IdentityUsersRoute
  '/openiddict/applications': typeof OpeniddictApplicationsRoute
  '/openiddict/scopes': typeof OpeniddictScopesRoute
  '/saas/editions': typeof SaasEditionsRoute
  '/account': typeof AccountIndexRoute
  '/file-management': typeof FileManagementIndexRoute
  '/identity': typeof IdentityIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/account': typeof AccountRouteRouteWithChildren
  '/identity': typeof IdentityRouteRouteWithChildren
  '/403': typeof R403Route
  '/audit-logs': typeof AuditLogsRoute
  '/background-jobs': typeof BackgroundJobsRoute
  '/books': typeof BooksRoute
  '/features': typeof FeaturesRoute
  '/gdpr': typeof GdprRoute
  '/profile': typeof ProfileRoute
  '/settings': typeof SettingsRoute
  '/tenants': typeof TenantsRoute
  '/account/forgot-password': typeof AccountForgotPasswordRoute
  '/account/login': typeof AccountLoginRoute
  '/account/register': typeof AccountRegisterRoute
  '/account/reset-password': typeof AccountResetPasswordRoute
  '/identity/permissions': typeof IdentityPermissionsRoute
  '/identity/roles': typeof IdentityRolesRoute
  '/identity/users': typeof IdentityUsersRoute
  '/openiddict/applications': typeof OpeniddictApplicationsRoute
  '/openiddict/scopes': typeof OpeniddictScopesRoute
  '/saas/editions': typeof SaasEditionsRoute
  '/account/': typeof AccountIndexRoute
  '/file-management/': typeof FileManagementIndexRoute
  '/identity/': typeof IdentityIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/identity'
    | '/403'
    | '/audit-logs'
    | '/background-jobs'
    | '/books'
    | '/features'
    | '/gdpr'
    | '/profile'
    | '/settings'
    | '/tenants'
    | '/account/forgot-password'
    | '/account/login'
    | '/account/register'
    | '/account/reset-password'
    | '/identity/permissions'
    | '/identity/roles'
    | '/identity/users'
    | '/openiddict/applications'
    | '/openiddict/scopes'
    | '/saas/editions'
    | '/account/'
    | '/file-management/'
    | '/identity/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/403'
    | '/audit-logs'
    | '/background-jobs'
    | '/books'
    | '/features'
    | '/gdpr'
    | '/profile'
    | '/settings'
    | '/tenants'
    | '/account/forgot-password'
    | '/account/login'
    | '/account/register'
    | '/account/reset-password'
    | '/identity/permissions'
    | '/identity/roles'
    | '/identity/users'
    | '/openiddict/applications'
    | '/openiddict/scopes'
    | '/saas/editions'
    | '/account'
    | '/file-management'
    | '/identity'
  id:
    | '__root__'
    | '/'
    | '/account'
    | '/identity'
    | '/403'
    | '/audit-logs'
    | '/background-jobs'
    | '/books'
    | '/features'
    | '/gdpr'
    | '/profile'
    | '/settings'
    | '/tenants'
    | '/account/forgot-password'
    | '/account/login'
    | '/account/register'
    | '/account/reset-password'
    | '/identity/permissions'
    | '/identity/roles'
    | '/identity/users'
    | '/openiddict/applications'
    | '/openiddict/scopes'
    | '/saas/editions'
    | '/account/'
    | '/file-management/'
    | '/identity/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountRouteRoute: typeof AccountRouteRouteWithChildren
  IdentityRouteRoute: typeof IdentityRouteRouteWithChildren
  R403Route: typeof R403Route
  AuditLogsRoute: typeof AuditLogsRoute
  BackgroundJobsRoute: typeof BackgroundJobsRoute
  BooksRoute: typeof BooksRoute
  FeaturesRoute: typeof FeaturesRoute
  GdprRoute: typeof GdprRoute
  ProfileRoute: typeof ProfileRoute
  SettingsRoute: typeof SettingsRoute
  TenantsRoute: typeof TenantsRoute
  OpeniddictApplicationsRoute: typeof OpeniddictApplicationsRoute
  OpeniddictScopesRoute: typeof OpeniddictScopesRoute
  SaasEditionsRoute: typeof SaasEditionsRoute
  FileManagementIndexRoute: typeof FileManagementIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/403': {
      id: '/403'
      path: '/403'
      fullPath: '/403'
      preLoaderRoute: typeof R403RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audit-logs': {
      id: '/audit-logs'
      path: '/audit-logs'
      fullPath: '/audit-logs'
      preLoaderRoute: typeof AuditLogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/background-jobs': {
      id: '/background-jobs'
      path: '/background-jobs'
      fullPath: '/background-jobs'
      preLoaderRoute: typeof BackgroundJobsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/books': {
      id: '/books'
      path: '/books'
      fullPath: '/books'
      preLoaderRoute: typeof BooksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/features': {
      id: '/features'
      path: '/features'
      fullPath: '/features'
      preLoaderRoute: typeof FeaturesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gdpr': {
      id: '/gdpr'
      path: '/gdpr'
      fullPath: '/gdpr'
      preLoaderRoute: typeof GdprRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/identity': {
      id: '/identity'
      path: '/identity'
      fullPath: '/identity'
      preLoaderRoute: typeof IdentityRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tenants': {
      id: '/tenants'
      path: '/tenants'
      fullPath: '/tenants'
      preLoaderRoute: typeof TenantsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/': {
      id: '/account/'
      path: '/'
      fullPath: '/account/'
      preLoaderRoute: typeof AccountIndexRouteImport
      parentRoute: typeof AccountRouteRoute
    }
    '/account/forgot-password': {
      id: '/account/forgot-password'
      path: '/forgot-password'
      fullPath: '/account/forgot-password'
      preLoaderRoute: typeof AccountForgotPasswordRouteImport
      parentRoute: typeof AccountRouteRoute
    }
    '/account/login': {
      id: '/account/login'
      path: '/login'
      fullPath: '/account/login'
      preLoaderRoute: typeof AccountLoginRouteImport
      parentRoute: typeof AccountRouteRoute
    }
    '/account/register': {
      id: '/account/register'
      path: '/register'
      fullPath: '/account/register'
      preLoaderRoute: typeof AccountRegisterRouteImport
      parentRoute: typeof AccountRouteRoute
    }
    '/account/reset-password': {
      id: '/account/reset-password'
      path: '/reset-password'
      fullPath: '/account/reset-password'
      preLoaderRoute: typeof AccountResetPasswordRouteImport
      parentRoute: typeof AccountRouteRoute
    }
    '/file-management/': {
      id: '/file-management/'
      path: '/file-management'
      fullPath: '/file-management/'
      preLoaderRoute: typeof FileManagementIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/identity/': {
      id: '/identity/'
      path: '/'
      fullPath: '/identity/'
      preLoaderRoute: typeof IdentityIndexRouteImport
      parentRoute: typeof IdentityRouteRoute
    }
    '/identity/permissions': {
      id: '/identity/permissions'
      path: '/permissions'
      fullPath: '/identity/permissions'
      preLoaderRoute: typeof IdentityPermissionsRouteImport
      parentRoute: typeof IdentityRouteRoute
    }
    '/identity/roles': {
      id: '/identity/roles'
      path: '/roles'
      fullPath: '/identity/roles'
      preLoaderRoute: typeof IdentityRolesRouteImport
      parentRoute: typeof IdentityRouteRoute
    }
    '/identity/users': {
      id: '/identity/users'
      path: '/users'
      fullPath: '/identity/users'
      preLoaderRoute: typeof IdentityUsersRouteImport
      parentRoute: typeof IdentityRouteRoute
    }
    '/openiddict/applications': {
      id: '/openiddict/applications'
      path: '/openiddict/applications'
      fullPath: '/openiddict/applications'
      preLoaderRoute: typeof OpeniddictApplicationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/openiddict/scopes': {
      id: '/openiddict/scopes'
      path: '/openiddict/scopes'
      fullPath: '/openiddict/scopes'
      preLoaderRoute: typeof OpeniddictScopesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/saas/editions': {
      id: '/saas/editions'
      path: '/saas/editions'
      fullPath: '/saas/editions'
      preLoaderRoute: typeof SaasEditionsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AccountRouteRouteChildren {
  AccountForgotPasswordRoute: typeof AccountForgotPasswordRoute
  AccountLoginRoute: typeof AccountLoginRoute
  AccountRegisterRoute: typeof AccountRegisterRoute
  AccountResetPasswordRoute: typeof AccountResetPasswordRoute
  AccountIndexRoute: typeof AccountIndexRoute
}

const AccountRouteRouteChildren: AccountRouteRouteChildren = {
  AccountForgotPasswordRoute: AccountForgotPasswordRoute,
  AccountLoginRoute: AccountLoginRoute,
  AccountRegisterRoute: AccountRegisterRoute,
  AccountResetPasswordRoute: AccountResetPasswordRoute,
  AccountIndexRoute: AccountIndexRoute,
}

const AccountRouteRouteWithChildren = AccountRouteRoute._addFileChildren(
  AccountRouteRouteChildren,
)

interface IdentityRouteRouteChildren {
  IdentityPermissionsRoute: typeof IdentityPermissionsRoute
  IdentityRolesRoute: typeof IdentityRolesRoute
  IdentityUsersRoute: typeof IdentityUsersRoute
  IdentityIndexRoute: typeof IdentityIndexRoute
}

const IdentityRouteRouteChildren: IdentityRouteRouteChildren = {
  IdentityPermissionsRoute: IdentityPermissionsRoute,
  IdentityRolesRoute: IdentityRolesRoute,
  IdentityUsersRoute: IdentityUsersRoute,
  IdentityIndexRoute: IdentityIndexRoute,
}

const IdentityRouteRouteWithChildren = IdentityRouteRoute._addFileChildren(
  IdentityRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountRouteRoute: AccountRouteRouteWithChildren,
  IdentityRouteRoute: IdentityRouteRouteWithChildren,
  R403Route: R403Route,
  AuditLogsRoute: AuditLogsRoute,
  BackgroundJobsRoute: BackgroundJobsRoute,
  BooksRoute: BooksRoute,
  FeaturesRoute: FeaturesRoute,
  GdprRoute: GdprRoute,
  ProfileRoute: ProfileRoute,
  SettingsRoute: SettingsRoute,
  TenantsRoute: TenantsRoute,
  OpeniddictApplicationsRoute: OpeniddictApplicationsRoute,
  OpeniddictScopesRoute: OpeniddictScopesRoute,
  SaasEditionsRoute: SaasEditionsRoute,
  FileManagementIndexRoute: FileManagementIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
