/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AccountRouteRouteImport } from './routes/account/route'
import { Route as AdminRouteRouteImport } from './routes/admin/route'
import { Route as ClassroomRouteRouteImport } from './routes/classroom/route'
import { Route as DevRouteRouteImport } from './routes/dev/route'
import { Route as PresentationRouteRouteImport } from './routes/presentation/route'
import { Route as StudentRouteRouteImport } from './routes/student/route'
import { Route as AccountIndexRouteImport } from './routes/account/index'
import { Route as AccountForgotPasswordRouteImport } from './routes/account/forgot-password'
import { Route as AccountLoginRouteImport } from './routes/account/login'
import { Route as AccountRegisterRouteImport } from './routes/account/register'
import { Route as AccountResetPasswordRouteImport } from './routes/account/reset-password'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as Admin403RouteImport } from './routes/admin/403'
import { Route as AdminAuditLogsRouteImport } from './routes/admin/audit-logs'
import { Route as AdminBackgroundJobsRouteImport } from './routes/admin/background-jobs'
import { Route as AdminBooksRouteImport } from './routes/admin/books'
import { Route as AdminChatRouteImport } from './routes/admin/chat'
import { Route as AdminFeaturesRouteImport } from './routes/admin/features'
import { Route as AdminIdentityRouteRouteImport } from './routes/admin/identity/route'
import { Route as AdminProfileRouteImport } from './routes/admin/profile'
import { Route as AdminSaasRouteRouteImport } from './routes/admin/saas/route'
import { Route as AdminSettingsRouteImport } from './routes/admin/settings'
import { Route as ClassroomIndexRouteImport } from './routes/classroom/index'
import { Route as ClassroomSessionIdRouteImport } from './routes/classroom/$sessionId'
import { Route as ClassroomQuestionsRouteImport } from './routes/classroom/questions'
import { Route as ClassroomQuizzesRouteImport } from './routes/classroom/quizzes'
import { Route as ClassroomSessionsRouteImport } from './routes/classroom/sessions'
import { Route as DevLeaderboardRouteImport } from './routes/dev/leaderboard'
import { Route as PresentationSessionIdRouteImport } from './routes/presentation/$sessionId'
import { Route as StudentJoinRouteImport } from './routes/student/join'
import { Route as AdminCmsBlogPostsRouteImport } from './routes/admin/cms/blog-posts'
import { Route as AdminCmsBlogsRouteImport } from './routes/admin/cms/blogs'
import { Route as AdminCmsCommentsRouteImport } from './routes/admin/cms/comments'
import { Route as AdminCmsMenusRouteImport } from './routes/admin/cms/menus'
import { Route as AdminCmsPagesRouteImport } from './routes/admin/cms/pages'
import { Route as AdminCmsTagsRouteImport } from './routes/admin/cms/tags'
import { Route as AdminFileManagementIndexRouteImport } from './routes/admin/file-management/index'
import { Route as AdminIdentityIndexRouteImport } from './routes/admin/identity/index'
import { Route as AdminIdentityClaimTypesRouteImport } from './routes/admin/identity/claim-types'
import { Route as AdminIdentityPermissionsRouteImport } from './routes/admin/identity/permissions'
import { Route as AdminIdentityRolesRouteImport } from './routes/admin/identity/roles'
import { Route as AdminIdentityUsersRouteImport } from './routes/admin/identity/users'
import { Route as AdminOpeniddictApplicationsRouteImport } from './routes/admin/openiddict/applications'
import { Route as AdminOpeniddictScopesRouteImport } from './routes/admin/openiddict/scopes'
import { Route as AdminSaasTenantsRouteImport } from './routes/admin/saas/tenants'
import { Route as StudentSessionsSessionIdRouteImport } from './routes/student/sessions/$sessionId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRouteRoute = AccountRouteRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const ClassroomRouteRoute = ClassroomRouteRouteImport.update({
  id: '/classroom',
  path: '/classroom',
  getParentRoute: () => rootRouteImport,
} as any)
const DevRouteRoute = DevRouteRouteImport.update({
  id: '/dev',
  path: '/dev',
  getParentRoute: () => rootRouteImport,
} as any)
const PresentationRouteRoute = PresentationRouteRouteImport.update({
  id: '/presentation',
  path: '/presentation',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentRouteRoute = StudentRouteRouteImport.update({
  id: '/student',
  path: '/student',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountIndexRoute = AccountIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AccountRouteRoute,
} as any)
const AccountForgotPasswordRoute = AccountForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => AccountRouteRoute,
} as any)
const AccountLoginRoute = AccountLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AccountRouteRoute,
} as any)
const AccountRegisterRoute = AccountRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => AccountRouteRoute,
} as any)
const AccountResetPasswordRoute = AccountResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => AccountRouteRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const Admin403Route = Admin403RouteImport.update({
  id: '/403',
  path: '/403',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminAuditLogsRoute = AdminAuditLogsRouteImport.update({
  id: '/audit-logs',
  path: '/audit-logs',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminBackgroundJobsRoute = AdminBackgroundJobsRouteImport.update({
  id: '/background-jobs',
  path: '/background-jobs',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminBooksRoute = AdminBooksRouteImport.update({
  id: '/books',
  path: '/books',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminChatRoute = AdminChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminFeaturesRoute = AdminFeaturesRouteImport.update({
  id: '/features',
  path: '/features',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminIdentityRouteRoute = AdminIdentityRouteRouteImport.update({
  id: '/identity',
  path: '/identity',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminProfileRoute = AdminProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminSaasRouteRoute = AdminSaasRouteRouteImport.update({
  id: '/saas',
  path: '/saas',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRouteRoute,
} as any)
const ClassroomIndexRoute = ClassroomIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ClassroomRouteRoute,
} as any)
const ClassroomSessionIdRoute = ClassroomSessionIdRouteImport.update({
  id: '/$sessionId',
  path: '/$sessionId',
  getParentRoute: () => ClassroomRouteRoute,
} as any)
const ClassroomQuestionsRoute = ClassroomQuestionsRouteImport.update({
  id: '/questions',
  path: '/questions',
  getParentRoute: () => ClassroomRouteRoute,
} as any)
const ClassroomQuizzesRoute = ClassroomQuizzesRouteImport.update({
  id: '/quizzes',
  path: '/quizzes',
  getParentRoute: () => ClassroomRouteRoute,
} as any)
const ClassroomSessionsRoute = ClassroomSessionsRouteImport.update({
  id: '/sessions',
  path: '/sessions',
  getParentRoute: () => ClassroomRouteRoute,
} as any)
const DevLeaderboardRoute = DevLeaderboardRouteImport.update({
  id: '/leaderboard',
  path: '/leaderboard',
  getParentRoute: () => DevRouteRoute,
} as any)
const PresentationSessionIdRoute = PresentationSessionIdRouteImport.update({
  id: '/$sessionId',
  path: '/$sessionId',
  getParentRoute: () => PresentationRouteRoute,
} as any)
const StudentJoinRoute = StudentJoinRouteImport.update({
  id: '/join',
  path: '/join',
  getParentRoute: () => StudentRouteRoute,
} as any)
const AdminCmsBlogPostsRoute = AdminCmsBlogPostsRouteImport.update({
  id: '/cms/blog-posts',
  path: '/cms/blog-posts',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminCmsBlogsRoute = AdminCmsBlogsRouteImport.update({
  id: '/cms/blogs',
  path: '/cms/blogs',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminCmsCommentsRoute = AdminCmsCommentsRouteImport.update({
  id: '/cms/comments',
  path: '/cms/comments',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminCmsMenusRoute = AdminCmsMenusRouteImport.update({
  id: '/cms/menus',
  path: '/cms/menus',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminCmsPagesRoute = AdminCmsPagesRouteImport.update({
  id: '/cms/pages',
  path: '/cms/pages',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminCmsTagsRoute = AdminCmsTagsRouteImport.update({
  id: '/cms/tags',
  path: '/cms/tags',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminFileManagementIndexRoute =
  AdminFileManagementIndexRouteImport.update({
    id: '/file-management/',
    path: '/file-management/',
    getParentRoute: () => AdminRouteRoute,
  } as any)
const AdminIdentityIndexRoute = AdminIdentityIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminIdentityRouteRoute,
} as any)
const AdminIdentityClaimTypesRoute = AdminIdentityClaimTypesRouteImport.update({
  id: '/claim-types',
  path: '/claim-types',
  getParentRoute: () => AdminIdentityRouteRoute,
} as any)
const AdminIdentityPermissionsRoute =
  AdminIdentityPermissionsRouteImport.update({
    id: '/permissions',
    path: '/permissions',
    getParentRoute: () => AdminIdentityRouteRoute,
  } as any)
const AdminIdentityRolesRoute = AdminIdentityRolesRouteImport.update({
  id: '/roles',
  path: '/roles',
  getParentRoute: () => AdminIdentityRouteRoute,
} as any)
const AdminIdentityUsersRoute = AdminIdentityUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminIdentityRouteRoute,
} as any)
const AdminOpeniddictApplicationsRoute =
  AdminOpeniddictApplicationsRouteImport.update({
    id: '/openiddict/applications',
    path: '/openiddict/applications',
    getParentRoute: () => AdminRouteRoute,
  } as any)
const AdminOpeniddictScopesRoute = AdminOpeniddictScopesRouteImport.update({
  id: '/openiddict/scopes',
  path: '/openiddict/scopes',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminSaasTenantsRoute = AdminSaasTenantsRouteImport.update({
  id: '/tenants',
  path: '/tenants',
  getParentRoute: () => AdminSaasRouteRoute,
} as any)
const StudentSessionsSessionIdRoute =
  StudentSessionsSessionIdRouteImport.update({
    id: '/sessions/$sessionId',
    path: '/sessions/$sessionId',
    getParentRoute: () => StudentRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account': typeof AccountRouteRouteWithChildren
  '/admin': typeof AdminRouteRouteWithChildren
  '/classroom': typeof ClassroomRouteRouteWithChildren
  '/dev': typeof DevRouteRouteWithChildren
  '/presentation': typeof PresentationRouteRouteWithChildren
  '/student': typeof StudentRouteRouteWithChildren
  '/admin/identity': typeof AdminIdentityRouteRouteWithChildren
  '/admin/saas': typeof AdminSaasRouteRouteWithChildren
  '/account/forgot-password': typeof AccountForgotPasswordRoute
  '/account/login': typeof AccountLoginRoute
  '/account/register': typeof AccountRegisterRoute
  '/account/reset-password': typeof AccountResetPasswordRoute
  '/admin/403': typeof Admin403Route
  '/admin/audit-logs': typeof AdminAuditLogsRoute
  '/admin/background-jobs': typeof AdminBackgroundJobsRoute
  '/admin/books': typeof AdminBooksRoute
  '/admin/chat': typeof AdminChatRoute
  '/admin/features': typeof AdminFeaturesRoute
  '/admin/profile': typeof AdminProfileRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/classroom/$sessionId': typeof ClassroomSessionIdRoute
  '/classroom/questions': typeof ClassroomQuestionsRoute
  '/classroom/quizzes': typeof ClassroomQuizzesRoute
  '/classroom/sessions': typeof ClassroomSessionsRoute
  '/dev/leaderboard': typeof DevLeaderboardRoute
  '/presentation/$sessionId': typeof PresentationSessionIdRoute
  '/student/join': typeof StudentJoinRoute
  '/account/': typeof AccountIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/classroom/': typeof ClassroomIndexRoute
  '/admin/cms/blog-posts': typeof AdminCmsBlogPostsRoute
  '/admin/cms/blogs': typeof AdminCmsBlogsRoute
  '/admin/cms/comments': typeof AdminCmsCommentsRoute
  '/admin/cms/menus': typeof AdminCmsMenusRoute
  '/admin/cms/pages': typeof AdminCmsPagesRoute
  '/admin/cms/tags': typeof AdminCmsTagsRoute
  '/admin/identity/claim-types': typeof AdminIdentityClaimTypesRoute
  '/admin/identity/permissions': typeof AdminIdentityPermissionsRoute
  '/admin/identity/roles': typeof AdminIdentityRolesRoute
  '/admin/identity/users': typeof AdminIdentityUsersRoute
  '/admin/openiddict/applications': typeof AdminOpeniddictApplicationsRoute
  '/admin/openiddict/scopes': typeof AdminOpeniddictScopesRoute
  '/admin/saas/tenants': typeof AdminSaasTenantsRoute
  '/student/sessions/$sessionId': typeof StudentSessionsSessionIdRoute
  '/admin/file-management/': typeof AdminFileManagementIndexRoute
  '/admin/identity/': typeof AdminIdentityIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dev': typeof DevRouteRouteWithChildren
  '/presentation': typeof PresentationRouteRouteWithChildren
  '/student': typeof StudentRouteRouteWithChildren
  '/admin/saas': typeof AdminSaasRouteRouteWithChildren
  '/account/forgot-password': typeof AccountForgotPasswordRoute
  '/account/login': typeof AccountLoginRoute
  '/account/register': typeof AccountRegisterRoute
  '/account/reset-password': typeof AccountResetPasswordRoute
  '/admin/403': typeof Admin403Route
  '/admin/audit-logs': typeof AdminAuditLogsRoute
  '/admin/background-jobs': typeof AdminBackgroundJobsRoute
  '/admin/books': typeof AdminBooksRoute
  '/admin/chat': typeof AdminChatRoute
  '/admin/features': typeof AdminFeaturesRoute
  '/admin/profile': typeof AdminProfileRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/classroom/$sessionId': typeof ClassroomSessionIdRoute
  '/classroom/questions': typeof ClassroomQuestionsRoute
  '/classroom/quizzes': typeof ClassroomQuizzesRoute
  '/classroom/sessions': typeof ClassroomSessionsRoute
  '/dev/leaderboard': typeof DevLeaderboardRoute
  '/presentation/$sessionId': typeof PresentationSessionIdRoute
  '/student/join': typeof StudentJoinRoute
  '/account': typeof AccountIndexRoute
  '/admin': typeof AdminIndexRoute
  '/classroom': typeof ClassroomIndexRoute
  '/admin/cms/blog-posts': typeof AdminCmsBlogPostsRoute
  '/admin/cms/blogs': typeof AdminCmsBlogsRoute
  '/admin/cms/comments': typeof AdminCmsCommentsRoute
  '/admin/cms/menus': typeof AdminCmsMenusRoute
  '/admin/cms/pages': typeof AdminCmsPagesRoute
  '/admin/cms/tags': typeof AdminCmsTagsRoute
  '/admin/identity/claim-types': typeof AdminIdentityClaimTypesRoute
  '/admin/identity/permissions': typeof AdminIdentityPermissionsRoute
  '/admin/identity/roles': typeof AdminIdentityRolesRoute
  '/admin/identity/users': typeof AdminIdentityUsersRoute
  '/admin/openiddict/applications': typeof AdminOpeniddictApplicationsRoute
  '/admin/openiddict/scopes': typeof AdminOpeniddictScopesRoute
  '/admin/saas/tenants': typeof AdminSaasTenantsRoute
  '/student/sessions/$sessionId': typeof StudentSessionsSessionIdRoute
  '/admin/file-management': typeof AdminFileManagementIndexRoute
  '/admin/identity': typeof AdminIdentityIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/account': typeof AccountRouteRouteWithChildren
  '/admin': typeof AdminRouteRouteWithChildren
  '/classroom': typeof ClassroomRouteRouteWithChildren
  '/dev': typeof DevRouteRouteWithChildren
  '/presentation': typeof PresentationRouteRouteWithChildren
  '/student': typeof StudentRouteRouteWithChildren
  '/admin/identity': typeof AdminIdentityRouteRouteWithChildren
  '/admin/saas': typeof AdminSaasRouteRouteWithChildren
  '/account/forgot-password': typeof AccountForgotPasswordRoute
  '/account/login': typeof AccountLoginRoute
  '/account/register': typeof AccountRegisterRoute
  '/account/reset-password': typeof AccountResetPasswordRoute
  '/admin/403': typeof Admin403Route
  '/admin/audit-logs': typeof AdminAuditLogsRoute
  '/admin/background-jobs': typeof AdminBackgroundJobsRoute
  '/admin/books': typeof AdminBooksRoute
  '/admin/chat': typeof AdminChatRoute
  '/admin/features': typeof AdminFeaturesRoute
  '/admin/profile': typeof AdminProfileRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/classroom/$sessionId': typeof ClassroomSessionIdRoute
  '/classroom/questions': typeof ClassroomQuestionsRoute
  '/classroom/quizzes': typeof ClassroomQuizzesRoute
  '/classroom/sessions': typeof ClassroomSessionsRoute
  '/dev/leaderboard': typeof DevLeaderboardRoute
  '/presentation/$sessionId': typeof PresentationSessionIdRoute
  '/student/join': typeof StudentJoinRoute
  '/account/': typeof AccountIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/classroom/': typeof ClassroomIndexRoute
  '/admin/cms/blog-posts': typeof AdminCmsBlogPostsRoute
  '/admin/cms/blogs': typeof AdminCmsBlogsRoute
  '/admin/cms/comments': typeof AdminCmsCommentsRoute
  '/admin/cms/menus': typeof AdminCmsMenusRoute
  '/admin/cms/pages': typeof AdminCmsPagesRoute
  '/admin/cms/tags': typeof AdminCmsTagsRoute
  '/admin/identity/claim-types': typeof AdminIdentityClaimTypesRoute
  '/admin/identity/permissions': typeof AdminIdentityPermissionsRoute
  '/admin/identity/roles': typeof AdminIdentityRolesRoute
  '/admin/identity/users': typeof AdminIdentityUsersRoute
  '/admin/openiddict/applications': typeof AdminOpeniddictApplicationsRoute
  '/admin/openiddict/scopes': typeof AdminOpeniddictScopesRoute
  '/admin/saas/tenants': typeof AdminSaasTenantsRoute
  '/student/sessions/$sessionId': typeof StudentSessionsSessionIdRoute
  '/admin/file-management/': typeof AdminFileManagementIndexRoute
  '/admin/identity/': typeof AdminIdentityIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/admin'
    | '/classroom'
    | '/dev'
    | '/presentation'
    | '/student'
    | '/admin/identity'
    | '/admin/saas'
    | '/account/forgot-password'
    | '/account/login'
    | '/account/register'
    | '/account/reset-password'
    | '/admin/403'
    | '/admin/audit-logs'
    | '/admin/background-jobs'
    | '/admin/books'
    | '/admin/chat'
    | '/admin/features'
    | '/admin/profile'
    | '/admin/settings'
    | '/classroom/$sessionId'
    | '/classroom/questions'
    | '/classroom/quizzes'
    | '/classroom/sessions'
    | '/dev/leaderboard'
    | '/presentation/$sessionId'
    | '/student/join'
    | '/account/'
    | '/admin/'
    | '/classroom/'
    | '/admin/cms/blog-posts'
    | '/admin/cms/blogs'
    | '/admin/cms/comments'
    | '/admin/cms/menus'
    | '/admin/cms/pages'
    | '/admin/cms/tags'
    | '/admin/identity/claim-types'
    | '/admin/identity/permissions'
    | '/admin/identity/roles'
    | '/admin/identity/users'
    | '/admin/openiddict/applications'
    | '/admin/openiddict/scopes'
    | '/admin/saas/tenants'
    | '/student/sessions/$sessionId'
    | '/admin/file-management/'
    | '/admin/identity/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dev'
    | '/presentation'
    | '/student'
    | '/admin/saas'
    | '/account/forgot-password'
    | '/account/login'
    | '/account/register'
    | '/account/reset-password'
    | '/admin/403'
    | '/admin/audit-logs'
    | '/admin/background-jobs'
    | '/admin/books'
    | '/admin/chat'
    | '/admin/features'
    | '/admin/profile'
    | '/admin/settings'
    | '/classroom/$sessionId'
    | '/classroom/questions'
    | '/classroom/quizzes'
    | '/classroom/sessions'
    | '/dev/leaderboard'
    | '/presentation/$sessionId'
    | '/student/join'
    | '/account'
    | '/admin'
    | '/classroom'
    | '/admin/cms/blog-posts'
    | '/admin/cms/blogs'
    | '/admin/cms/comments'
    | '/admin/cms/menus'
    | '/admin/cms/pages'
    | '/admin/cms/tags'
    | '/admin/identity/claim-types'
    | '/admin/identity/permissions'
    | '/admin/identity/roles'
    | '/admin/identity/users'
    | '/admin/openiddict/applications'
    | '/admin/openiddict/scopes'
    | '/admin/saas/tenants'
    | '/student/sessions/$sessionId'
    | '/admin/file-management'
    | '/admin/identity'
  id:
    | '__root__'
    | '/'
    | '/account'
    | '/admin'
    | '/classroom'
    | '/dev'
    | '/presentation'
    | '/student'
    | '/admin/identity'
    | '/admin/saas'
    | '/account/forgot-password'
    | '/account/login'
    | '/account/register'
    | '/account/reset-password'
    | '/admin/403'
    | '/admin/audit-logs'
    | '/admin/background-jobs'
    | '/admin/books'
    | '/admin/chat'
    | '/admin/features'
    | '/admin/profile'
    | '/admin/settings'
    | '/classroom/$sessionId'
    | '/classroom/questions'
    | '/classroom/quizzes'
    | '/classroom/sessions'
    | '/dev/leaderboard'
    | '/presentation/$sessionId'
    | '/student/join'
    | '/account/'
    | '/admin/'
    | '/classroom/'
    | '/admin/cms/blog-posts'
    | '/admin/cms/blogs'
    | '/admin/cms/comments'
    | '/admin/cms/menus'
    | '/admin/cms/pages'
    | '/admin/cms/tags'
    | '/admin/identity/claim-types'
    | '/admin/identity/permissions'
    | '/admin/identity/roles'
    | '/admin/identity/users'
    | '/admin/openiddict/applications'
    | '/admin/openiddict/scopes'
    | '/admin/saas/tenants'
    | '/student/sessions/$sessionId'
    | '/admin/file-management/'
    | '/admin/identity/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountRouteRoute: typeof AccountRouteRouteWithChildren
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  ClassroomRouteRoute: typeof ClassroomRouteRouteWithChildren
  DevRouteRoute: typeof DevRouteRouteWithChildren
  PresentationRouteRoute: typeof PresentationRouteRouteWithChildren
  StudentRouteRoute: typeof StudentRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/classroom': {
      id: '/classroom'
      path: '/classroom'
      fullPath: '/classroom'
      preLoaderRoute: typeof ClassroomRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dev': {
      id: '/dev'
      path: '/dev'
      fullPath: '/dev'
      preLoaderRoute: typeof DevRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/presentation': {
      id: '/presentation'
      path: '/presentation'
      fullPath: '/presentation'
      preLoaderRoute: typeof PresentationRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student': {
      id: '/student'
      path: '/student'
      fullPath: '/student'
      preLoaderRoute: typeof StudentRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/': {
      id: '/account/'
      path: '/'
      fullPath: '/account/'
      preLoaderRoute: typeof AccountIndexRouteImport
      parentRoute: typeof AccountRouteRoute
    }
    '/account/forgot-password': {
      id: '/account/forgot-password'
      path: '/forgot-password'
      fullPath: '/account/forgot-password'
      preLoaderRoute: typeof AccountForgotPasswordRouteImport
      parentRoute: typeof AccountRouteRoute
    }
    '/account/login': {
      id: '/account/login'
      path: '/login'
      fullPath: '/account/login'
      preLoaderRoute: typeof AccountLoginRouteImport
      parentRoute: typeof AccountRouteRoute
    }
    '/account/register': {
      id: '/account/register'
      path: '/register'
      fullPath: '/account/register'
      preLoaderRoute: typeof AccountRegisterRouteImport
      parentRoute: typeof AccountRouteRoute
    }
    '/account/reset-password': {
      id: '/account/reset-password'
      path: '/reset-password'
      fullPath: '/account/reset-password'
      preLoaderRoute: typeof AccountResetPasswordRouteImport
      parentRoute: typeof AccountRouteRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/403': {
      id: '/admin/403'
      path: '/403'
      fullPath: '/admin/403'
      preLoaderRoute: typeof Admin403RouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/audit-logs': {
      id: '/admin/audit-logs'
      path: '/audit-logs'
      fullPath: '/admin/audit-logs'
      preLoaderRoute: typeof AdminAuditLogsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/background-jobs': {
      id: '/admin/background-jobs'
      path: '/background-jobs'
      fullPath: '/admin/background-jobs'
      preLoaderRoute: typeof AdminBackgroundJobsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/books': {
      id: '/admin/books'
      path: '/books'
      fullPath: '/admin/books'
      preLoaderRoute: typeof AdminBooksRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/chat': {
      id: '/admin/chat'
      path: '/chat'
      fullPath: '/admin/chat'
      preLoaderRoute: typeof AdminChatRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/features': {
      id: '/admin/features'
      path: '/features'
      fullPath: '/admin/features'
      preLoaderRoute: typeof AdminFeaturesRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/identity': {
      id: '/admin/identity'
      path: '/identity'
      fullPath: '/admin/identity'
      preLoaderRoute: typeof AdminIdentityRouteRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/profile': {
      id: '/admin/profile'
      path: '/profile'
      fullPath: '/admin/profile'
      preLoaderRoute: typeof AdminProfileRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/saas': {
      id: '/admin/saas'
      path: '/saas'
      fullPath: '/admin/saas'
      preLoaderRoute: typeof AdminSaasRouteRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/classroom/': {
      id: '/classroom/'
      path: '/'
      fullPath: '/classroom/'
      preLoaderRoute: typeof ClassroomIndexRouteImport
      parentRoute: typeof ClassroomRouteRoute
    }
    '/classroom/$sessionId': {
      id: '/classroom/$sessionId'
      path: '/$sessionId'
      fullPath: '/classroom/$sessionId'
      preLoaderRoute: typeof ClassroomSessionIdRouteImport
      parentRoute: typeof ClassroomRouteRoute
    }
    '/classroom/questions': {
      id: '/classroom/questions'
      path: '/questions'
      fullPath: '/classroom/questions'
      preLoaderRoute: typeof ClassroomQuestionsRouteImport
      parentRoute: typeof ClassroomRouteRoute
    }
    '/classroom/quizzes': {
      id: '/classroom/quizzes'
      path: '/quizzes'
      fullPath: '/classroom/quizzes'
      preLoaderRoute: typeof ClassroomQuizzesRouteImport
      parentRoute: typeof ClassroomRouteRoute
    }
    '/classroom/sessions': {
      id: '/classroom/sessions'
      path: '/sessions'
      fullPath: '/classroom/sessions'
      preLoaderRoute: typeof ClassroomSessionsRouteImport
      parentRoute: typeof ClassroomRouteRoute
    }
    '/dev/leaderboard': {
      id: '/dev/leaderboard'
      path: '/leaderboard'
      fullPath: '/dev/leaderboard'
      preLoaderRoute: typeof DevLeaderboardRouteImport
      parentRoute: typeof DevRouteRoute
    }
    '/presentation/$sessionId': {
      id: '/presentation/$sessionId'
      path: '/$sessionId'
      fullPath: '/presentation/$sessionId'
      preLoaderRoute: typeof PresentationSessionIdRouteImport
      parentRoute: typeof PresentationRouteRoute
    }
    '/student/join': {
      id: '/student/join'
      path: '/join'
      fullPath: '/student/join'
      preLoaderRoute: typeof StudentJoinRouteImport
      parentRoute: typeof StudentRouteRoute
    }
    '/admin/cms/blog-posts': {
      id: '/admin/cms/blog-posts'
      path: '/cms/blog-posts'
      fullPath: '/admin/cms/blog-posts'
      preLoaderRoute: typeof AdminCmsBlogPostsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/cms/blogs': {
      id: '/admin/cms/blogs'
      path: '/cms/blogs'
      fullPath: '/admin/cms/blogs'
      preLoaderRoute: typeof AdminCmsBlogsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/cms/comments': {
      id: '/admin/cms/comments'
      path: '/cms/comments'
      fullPath: '/admin/cms/comments'
      preLoaderRoute: typeof AdminCmsCommentsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/cms/menus': {
      id: '/admin/cms/menus'
      path: '/cms/menus'
      fullPath: '/admin/cms/menus'
      preLoaderRoute: typeof AdminCmsMenusRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/cms/pages': {
      id: '/admin/cms/pages'
      path: '/cms/pages'
      fullPath: '/admin/cms/pages'
      preLoaderRoute: typeof AdminCmsPagesRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/cms/tags': {
      id: '/admin/cms/tags'
      path: '/cms/tags'
      fullPath: '/admin/cms/tags'
      preLoaderRoute: typeof AdminCmsTagsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/file-management/': {
      id: '/admin/file-management/'
      path: '/file-management'
      fullPath: '/admin/file-management/'
      preLoaderRoute: typeof AdminFileManagementIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/identity/': {
      id: '/admin/identity/'
      path: '/'
      fullPath: '/admin/identity/'
      preLoaderRoute: typeof AdminIdentityIndexRouteImport
      parentRoute: typeof AdminIdentityRouteRoute
    }
    '/admin/identity/claim-types': {
      id: '/admin/identity/claim-types'
      path: '/claim-types'
      fullPath: '/admin/identity/claim-types'
      preLoaderRoute: typeof AdminIdentityClaimTypesRouteImport
      parentRoute: typeof AdminIdentityRouteRoute
    }
    '/admin/identity/permissions': {
      id: '/admin/identity/permissions'
      path: '/permissions'
      fullPath: '/admin/identity/permissions'
      preLoaderRoute: typeof AdminIdentityPermissionsRouteImport
      parentRoute: typeof AdminIdentityRouteRoute
    }
    '/admin/identity/roles': {
      id: '/admin/identity/roles'
      path: '/roles'
      fullPath: '/admin/identity/roles'
      preLoaderRoute: typeof AdminIdentityRolesRouteImport
      parentRoute: typeof AdminIdentityRouteRoute
    }
    '/admin/identity/users': {
      id: '/admin/identity/users'
      path: '/users'
      fullPath: '/admin/identity/users'
      preLoaderRoute: typeof AdminIdentityUsersRouteImport
      parentRoute: typeof AdminIdentityRouteRoute
    }
    '/admin/openiddict/applications': {
      id: '/admin/openiddict/applications'
      path: '/openiddict/applications'
      fullPath: '/admin/openiddict/applications'
      preLoaderRoute: typeof AdminOpeniddictApplicationsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/openiddict/scopes': {
      id: '/admin/openiddict/scopes'
      path: '/openiddict/scopes'
      fullPath: '/admin/openiddict/scopes'
      preLoaderRoute: typeof AdminOpeniddictScopesRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/saas/tenants': {
      id: '/admin/saas/tenants'
      path: '/tenants'
      fullPath: '/admin/saas/tenants'
      preLoaderRoute: typeof AdminSaasTenantsRouteImport
      parentRoute: typeof AdminSaasRouteRoute
    }
    '/student/sessions/$sessionId': {
      id: '/student/sessions/$sessionId'
      path: '/sessions/$sessionId'
      fullPath: '/student/sessions/$sessionId'
      preLoaderRoute: typeof StudentSessionsSessionIdRouteImport
      parentRoute: typeof StudentRouteRoute
    }
  }
}

interface AccountRouteRouteChildren {
  AccountForgotPasswordRoute: typeof AccountForgotPasswordRoute
  AccountLoginRoute: typeof AccountLoginRoute
  AccountRegisterRoute: typeof AccountRegisterRoute
  AccountResetPasswordRoute: typeof AccountResetPasswordRoute
  AccountIndexRoute: typeof AccountIndexRoute
}

const AccountRouteRouteChildren: AccountRouteRouteChildren = {
  AccountForgotPasswordRoute: AccountForgotPasswordRoute,
  AccountLoginRoute: AccountLoginRoute,
  AccountRegisterRoute: AccountRegisterRoute,
  AccountResetPasswordRoute: AccountResetPasswordRoute,
  AccountIndexRoute: AccountIndexRoute,
}

const AccountRouteRouteWithChildren = AccountRouteRoute._addFileChildren(
  AccountRouteRouteChildren,
)

interface AdminIdentityRouteRouteChildren {
  AdminIdentityClaimTypesRoute: typeof AdminIdentityClaimTypesRoute
  AdminIdentityPermissionsRoute: typeof AdminIdentityPermissionsRoute
  AdminIdentityRolesRoute: typeof AdminIdentityRolesRoute
  AdminIdentityUsersRoute: typeof AdminIdentityUsersRoute
  AdminIdentityIndexRoute: typeof AdminIdentityIndexRoute
}

const AdminIdentityRouteRouteChildren: AdminIdentityRouteRouteChildren = {
  AdminIdentityClaimTypesRoute: AdminIdentityClaimTypesRoute,
  AdminIdentityPermissionsRoute: AdminIdentityPermissionsRoute,
  AdminIdentityRolesRoute: AdminIdentityRolesRoute,
  AdminIdentityUsersRoute: AdminIdentityUsersRoute,
  AdminIdentityIndexRoute: AdminIdentityIndexRoute,
}

const AdminIdentityRouteRouteWithChildren =
  AdminIdentityRouteRoute._addFileChildren(AdminIdentityRouteRouteChildren)

interface AdminSaasRouteRouteChildren {
  AdminSaasTenantsRoute: typeof AdminSaasTenantsRoute
}

const AdminSaasRouteRouteChildren: AdminSaasRouteRouteChildren = {
  AdminSaasTenantsRoute: AdminSaasTenantsRoute,
}

const AdminSaasRouteRouteWithChildren = AdminSaasRouteRoute._addFileChildren(
  AdminSaasRouteRouteChildren,
)

interface AdminRouteRouteChildren {
  AdminIdentityRouteRoute: typeof AdminIdentityRouteRouteWithChildren
  AdminSaasRouteRoute: typeof AdminSaasRouteRouteWithChildren
  Admin403Route: typeof Admin403Route
  AdminAuditLogsRoute: typeof AdminAuditLogsRoute
  AdminBackgroundJobsRoute: typeof AdminBackgroundJobsRoute
  AdminBooksRoute: typeof AdminBooksRoute
  AdminChatRoute: typeof AdminChatRoute
  AdminFeaturesRoute: typeof AdminFeaturesRoute
  AdminProfileRoute: typeof AdminProfileRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminCmsBlogPostsRoute: typeof AdminCmsBlogPostsRoute
  AdminCmsBlogsRoute: typeof AdminCmsBlogsRoute
  AdminCmsCommentsRoute: typeof AdminCmsCommentsRoute
  AdminCmsMenusRoute: typeof AdminCmsMenusRoute
  AdminCmsPagesRoute: typeof AdminCmsPagesRoute
  AdminCmsTagsRoute: typeof AdminCmsTagsRoute
  AdminOpeniddictApplicationsRoute: typeof AdminOpeniddictApplicationsRoute
  AdminOpeniddictScopesRoute: typeof AdminOpeniddictScopesRoute
  AdminFileManagementIndexRoute: typeof AdminFileManagementIndexRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminIdentityRouteRoute: AdminIdentityRouteRouteWithChildren,
  AdminSaasRouteRoute: AdminSaasRouteRouteWithChildren,
  Admin403Route: Admin403Route,
  AdminAuditLogsRoute: AdminAuditLogsRoute,
  AdminBackgroundJobsRoute: AdminBackgroundJobsRoute,
  AdminBooksRoute: AdminBooksRoute,
  AdminChatRoute: AdminChatRoute,
  AdminFeaturesRoute: AdminFeaturesRoute,
  AdminProfileRoute: AdminProfileRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminCmsBlogPostsRoute: AdminCmsBlogPostsRoute,
  AdminCmsBlogsRoute: AdminCmsBlogsRoute,
  AdminCmsCommentsRoute: AdminCmsCommentsRoute,
  AdminCmsMenusRoute: AdminCmsMenusRoute,
  AdminCmsPagesRoute: AdminCmsPagesRoute,
  AdminCmsTagsRoute: AdminCmsTagsRoute,
  AdminOpeniddictApplicationsRoute: AdminOpeniddictApplicationsRoute,
  AdminOpeniddictScopesRoute: AdminOpeniddictScopesRoute,
  AdminFileManagementIndexRoute: AdminFileManagementIndexRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

interface ClassroomRouteRouteChildren {
  ClassroomSessionIdRoute: typeof ClassroomSessionIdRoute
  ClassroomQuestionsRoute: typeof ClassroomQuestionsRoute
  ClassroomQuizzesRoute: typeof ClassroomQuizzesRoute
  ClassroomSessionsRoute: typeof ClassroomSessionsRoute
  ClassroomIndexRoute: typeof ClassroomIndexRoute
}

const ClassroomRouteRouteChildren: ClassroomRouteRouteChildren = {
  ClassroomSessionIdRoute: ClassroomSessionIdRoute,
  ClassroomQuestionsRoute: ClassroomQuestionsRoute,
  ClassroomQuizzesRoute: ClassroomQuizzesRoute,
  ClassroomSessionsRoute: ClassroomSessionsRoute,
  ClassroomIndexRoute: ClassroomIndexRoute,
}

const ClassroomRouteRouteWithChildren = ClassroomRouteRoute._addFileChildren(
  ClassroomRouteRouteChildren,
)

interface DevRouteRouteChildren {
  DevLeaderboardRoute: typeof DevLeaderboardRoute
}

const DevRouteRouteChildren: DevRouteRouteChildren = {
  DevLeaderboardRoute: DevLeaderboardRoute,
}

const DevRouteRouteWithChildren = DevRouteRoute._addFileChildren(
  DevRouteRouteChildren,
)

interface PresentationRouteRouteChildren {
  PresentationSessionIdRoute: typeof PresentationSessionIdRoute
}

const PresentationRouteRouteChildren: PresentationRouteRouteChildren = {
  PresentationSessionIdRoute: PresentationSessionIdRoute,
}

const PresentationRouteRouteWithChildren =
  PresentationRouteRoute._addFileChildren(PresentationRouteRouteChildren)

interface StudentRouteRouteChildren {
  StudentJoinRoute: typeof StudentJoinRoute
  StudentSessionsSessionIdRoute: typeof StudentSessionsSessionIdRoute
}

const StudentRouteRouteChildren: StudentRouteRouteChildren = {
  StudentJoinRoute: StudentJoinRoute,
  StudentSessionsSessionIdRoute: StudentSessionsSessionIdRoute,
}

const StudentRouteRouteWithChildren = StudentRouteRoute._addFileChildren(
  StudentRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountRouteRoute: AccountRouteRouteWithChildren,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  ClassroomRouteRoute: ClassroomRouteRouteWithChildren,
  DevRouteRoute: DevRouteRouteWithChildren,
  PresentationRouteRoute: PresentationRouteRouteWithChildren,
  StudentRouteRoute: StudentRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
