/* oxlint-disable */

export type { VoloAbpApplicationDtosListResultDto1VoloCmsKitPublicCommentsCommentWithDetailsDtoVoloCmsKitPublicApplicationContractsVersion10500CultureneutralPublicKeyTokennull } from "./commentWithDetailsDtoVolo/cmsKit/public/application/ContractsVersion10500CultureneutralPublicKeyTokennull.ts";
