/* oxlint-disable */

export type { VoloAbpApplicationDtosListResultDto1AcroStackServicesDtosFileManagementFileEntryDtoAcroStackVersion1000CultureneutralPublicKeyTokennull } from "./dtos/fileManagement/FileEntryDtoAcroStackVersion1000CultureneutralPublicKeyTokennull.ts";
export type { VoloAbpApplicationDtosListResultDto1AcroStackServicesDtosFileManagementFileFolderDtoAcroStackVersion1000CultureneutralPublicKeyTokennull } from "./dtos/fileManagement/FileFolderDtoAcroStackVersion1000CultureneutralPublicKeyTokennull.ts";
