/* oxlint-disable */

export type { VoloAbpApplicationDtosPagedResultDto1VoloAbpIdentityIdentityRoleDtoVoloAbpIdentityApplicationContractsVersion10500CultureneutralPublicKeyTokennull } from "./identity/application/ContractsVersion10500CultureneutralPublicKeyTokennull.ts";
