/* oxlint-disable */

export type { VoloAbpApplicationDtosPagedResultDto1VoloAbpIdentityIdentityRoleDtoVoloAbpIdentityApplicationContractsVersion10500CultureneutralPublicKeyTokennull } from "./application/ContractsVersion10500CultureneutralPublicKeyTokennull.ts";
