/* oxlint-disable */

export type { VoloAbpApplicationDtosPagedResultDto1VoloAbpTenantManagementTenantDtoVoloAbpTenantManagementApplicationContractsVersion10500CultureneutralPublicKeyTokennull } from "./ContractsVersion10500CultureneutralPublicKeyTokennull.ts";
