/* oxlint-disable */

export type { VoloAbpApplicationDtosPagedResultDto1VoloAbpIdentityIdentityRoleDtoVoloAbpIdentityApplicationContractsVersion10500CultureneutralPublicKeyTokennull } from "./abp/identity/application/ContractsVersion10500CultureneutralPublicKeyTokennull.ts";
