/* oxlint-disable */

export type { VoloAbpApplicationDtosListResultDto1VoloAbpIdentityIdentityRoleDtoVoloAbpIdentityApplicationContractsVersion10400CultureneutralPublicKeyTokennull } from "./abp/identity/application/ContractsVersion10400CultureneutralPublicKeyTokennull.ts";
