/* oxlint-disable */

export type { VoloAbpApplicationDtosListResultDto1VoloAbpIdentityIdentityRoleDtoVoloAbpIdentityApplicationContractsVersion10600CultureneutralPublicKeyTokennull } from "./abp/identity/application/ContractsVersion10600CultureneutralPublicKeyTokennull.ts";
