<Project Sdk="Microsoft.NET.Sdk">

  <Import Project="..\..\common.props" />

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <GenerateEmbeddedFilesManifest>true</GenerateEmbeddedFilesManifest>
    <RootNamespace>AcroStack</RootNamespace>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Volo.Abp.Localization" Version="10.6.0" />
    <PackageReference Include="Volo.Abp.Ddd.Application" Version="10.6.0" />
    <PackageReference Include="Microsoft.Extensions.FileProviders.Embedded" Version="10.0.9" />
  </ItemGroup>

  <ItemGroup>
    <Content Remove="Localization\AcroStack\*.json" />
    <EmbeddedResource Include="Localization\AcroStack\*.json" />
  </ItemGroup>

</Project>
