/* oxlint-disable */

export type { VoloAbpApplicationDtosListResultDto1VoloCmsKitMenusMenuItemDtoVoloCmsKitCommonApplicationContractsVersion10500CultureneutralPublicKeyTokennull } from "./common/application/ContractsVersion10500CultureneutralPublicKeyTokennull.ts";
