/* oxlint-disable */

export type { VoloAbpApplicationDtosPagedResultDto1VoloCmsKitAdminPagesPageDtoVoloCmsKitAdminApplicationContractsVersion10500CultureneutralPublicKeyTokennull } from "./admin/application/ContractsVersion10500CultureneutralPublicKeyTokennull.ts";
