/**
 * 聊天页共享样式：侧栏、消息气泡、搜索面板、输入区等。
 * 页面与各子组件统一从这里取样式，避免重复定义。
 */
import { makeStyles, tokens } from "@fluentui/react-components";

export const useChatStyles = makeStyles({
  root: {
    display: "flex",
    height: "calc(100vh - 220px)",
    minHeight: "480px",
    border: `1px solid ${tokens.colorNeutralStroke2}`,
    borderRadius: tokens.borderRadiusMedium,
    overflow: "hidden",
    backgroundColor: tokens.colorNeutralBackground1,
  },
  sidebar: {
    display: "flex",
    flexDirection: "column",
    width: "320px",
    minWidth: "260px",
    borderRight: `1px solid ${tokens.colorNeutralStroke2}`,
    backgroundColor: tokens.colorNeutralBackground2,
  },
  sidebarHeader: {
    display: "flex",
    flexDirection: "column",
    gap: tokens.spacingVerticalXS,
    padding: tokens.spacingHorizontalM,
  },
  sidebarTabs: {
    display: "flex",
    gap: tokens.spacingHorizontalXS,
  },
  sidebarList: {
    flex: 1,
    overflowY: "auto",
  },
  conversationItem: {
    display: "flex",
    alignItems: "center",
    gap: tokens.spacingHorizontalS,
    padding: `${tokens.spacingVerticalS} ${tokens.spacingHorizontalM}`,
    cursor: "pointer",
    width: "100%",
    border: "none",
    backgroundColor: "transparent",
    textAlign: "left" as const,
    "&:hover": {
      backgroundColor: tokens.colorNeutralBackground1Hover,
    },
  },
  conversationItemSelected: {
    backgroundColor: tokens.colorBrandBackground2,
    "&:hover": {
      backgroundColor: tokens.colorBrandBackground2Hover,
    },
  },
  conversationMeta: {
    display: "flex",
    flexDirection: "column",
    flex: 1,
    minWidth: 0,
  },
  conversationTop: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    gap: tokens.spacingHorizontalS,
  },
  conversationName: {
    fontWeight: "semibold",
    whiteSpace: "nowrap",
    overflow: "hidden",
    textOverflow: "ellipsis",
  },
  conversationNameUnread: {
    color: tokens.colorBrandForeground1,
  },
  conversationTime: {
    color: tokens.colorNeutralForeground3,
    fontSize: tokens.fontSizeBase200,
    flexShrink: 0,
  },
  conversationPreview: {
    color: tokens.colorNeutralForeground2,
    fontSize: tokens.fontSizeBase200,
    whiteSpace: "nowrap",
    overflow: "hidden",
    textOverflow: "ellipsis",
  },
  emptyPane: {
    display: "flex",
    flex: 1,
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "center",
    gap: tokens.spacingVerticalM,
    color: tokens.colorNeutralForeground3,
    padding: tokens.spacingHorizontalXXL,
  },
  messagePane: {
    display: "flex",
    flexDirection: "column",
    flex: 1,
    minWidth: 0,
  },
  messageHeader: {
    display: "flex",
    alignItems: "center",
    gap: tokens.spacingHorizontalS,
    padding: `${tokens.spacingVerticalS} ${tokens.spacingHorizontalM}`,
    borderBottom: `1px solid ${tokens.colorNeutralStroke2}`,
    backgroundColor: tokens.colorNeutralBackground1,
  },
  messageList: {
    flex: 1,
    overflowY: "auto",
    padding: tokens.spacingHorizontalM,
    display: "flex",
    flexDirection: "column",
    gap: tokens.spacingVerticalS,
  },
  bubbleRow: {
    display: "flex",
    width: "100%",
  },
  bubbleRowSent: {
    justifyContent: "flex-end",
  },
  bubbleRowReceived: {
    justifyContent: "flex-start",
  },
  bubble: {
    maxWidth: "70%",
    padding: `${tokens.spacingVerticalXS} ${tokens.spacingHorizontalM}`,
    borderRadius: tokens.borderRadiusMedium,
    wordBreak: "break-word",
    whiteSpace: "pre-wrap",
  },
  bubbleSent: {
    backgroundColor: tokens.colorBrandBackground,
    color: tokens.colorNeutralForegroundOnBrand,
    borderBottomRightRadius: tokens.borderRadiusNone,
  },
  bubbleReceived: {
    backgroundColor: tokens.colorNeutralBackground3,
    color: tokens.colorNeutralForeground1,
    borderBottomLeftRadius: tokens.borderRadiusNone,
  },
  bubbleMeta: {
    fontSize: tokens.fontSizeBase200,
    color: tokens.colorNeutralForeground3,
    marginTop: tokens.spacingVerticalXXS,
  },
  composer: {
    display: "flex",
    gap: tokens.spacingHorizontalS,
    padding: tokens.spacingHorizontalM,
    borderTop: `1px solid ${tokens.colorNeutralStroke2}`,
    backgroundColor: tokens.colorNeutralBackground1,
  },
  composerInput: {
    flex: 1,
  },
  badgeCount: {
    minWidth: "20px",
    height: "20px",
  },
  contactPicker: {
    display: "flex",
    flexDirection: "column",
    flex: 1,
    padding: tokens.spacingHorizontalM,
    gap: tokens.spacingVerticalS,
  },
  // ---- 增强功能 ----
  sidebarItemInner: {
    position: "relative" as const,
    display: "flex",
    alignItems: "center",
    gap: tokens.spacingHorizontalS,
    flex: 1,
    minWidth: 0,
  },
  presenceDot: {
    position: "absolute" as const,
    right: "-2px",
    bottom: "-2px",
    transform: "scale(0.85)",
    transformOrigin: "bottom right",
  },
  blockedTag: {
    fontSize: tokens.fontSizeBase100,
    color: tokens.colorNeutralForeground3,
    fontStyle: "italic",
  },
  messageHeaderRow: {
    display: "flex",
    alignItems: "center",
    gap: tokens.spacingHorizontalS,
    flex: 1,
    minWidth: 0,
  },
  headerSearchBox: {
    maxWidth: "260px",
    marginLeft: "auto",
  },
  searchResultsPanel: {
    position: "relative" as const,
    padding: `${tokens.spacingVerticalS} ${tokens.spacingHorizontalM}`,
    borderBottom: `1px solid ${tokens.colorNeutralStroke2}`,
    backgroundColor: tokens.colorNeutralBackground2,
    maxHeight: "200px",
    overflowY: "auto",
  },
  searchResultRow: {
    display: "flex",
    flexDirection: "column",
    gap: tokens.spacingVerticalXXS,
    padding: `${tokens.spacingVerticalXS} ${tokens.spacingHorizontalS}`,
    borderRadius: tokens.borderRadiusMedium,
    cursor: "pointer",
    border: "none",
    backgroundColor: "transparent",
    textAlign: "left" as const,
    width: "100%",
    "&:hover": {
      backgroundColor: tokens.colorNeutralBackground1Hover,
    },
  },
  searchResultText: {
    fontSize: tokens.fontSizeBase200,
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  searchResultMeta: {
    fontSize: tokens.fontSizeBase100,
    color: tokens.colorNeutralForeground3,
  },
  searchHighlight: {
    backgroundColor: tokens.colorPaletteGoldBackground2,
    color: tokens.colorNeutralForeground1,
    borderRadius: tokens.borderRadiusSmall,
    padding: "0 2px",
  },
  bubbleWrapper: {
    position: "relative" as const,
    display: "inline-flex",
    flexDirection: "column",
    maxWidth: "70%",
  },
  bubbleActions: {
    position: "absolute" as const,
    top: "-12px",
    right: "0",
    display: "flex",
    gap: tokens.spacingHorizontalXXS,
    backgroundColor: tokens.colorNeutralBackground1,
    borderRadius: tokens.borderRadiusCircular,
    boxShadow: tokens.shadow2,
    padding: "2px",
    opacity: 0,
    transition: "opacity 0.15s ease",
    zIndex: 1,
    pointerEvents: "none" as const,
  },
  bubbleActionsVisible: {
    opacity: 1,
    pointerEvents: "auto" as const,
  },
  bubbleActionButton: {
    minWidth: "24px",
    height: "24px",
    padding: "0",
    borderRadius: tokens.borderRadiusCircular,
  },
  reactionPicker: {
    display: "flex",
    gap: tokens.spacingHorizontalXXS,
    padding: `${tokens.spacingVerticalXXS} ${tokens.spacingHorizontalXS}`,
    backgroundColor: tokens.colorNeutralBackground1,
    borderRadius: tokens.borderRadiusCircular,
    boxShadow: tokens.shadow2,
    marginTop: tokens.spacingVerticalXXS,
  },
  reactionPickerButton: {
    minWidth: "28px",
    height: "28px",
    padding: "0",
    fontSize: "16px",
    lineHeight: 1,
    borderRadius: tokens.borderRadiusCircular,
  },
  reactionsList: {
    display: "flex",
    flexWrap: "wrap",
    gap: tokens.spacingHorizontalXXS,
    marginTop: tokens.spacingVerticalXXS,
  },
  reactionChip: {
    display: "inline-flex",
    alignItems: "center",
    gap: tokens.spacingHorizontalXXS,
    padding: "1px 6px",
    borderRadius: tokens.borderRadiusCircular,
    border: `1px solid ${tokens.colorNeutralStroke1}`,
    backgroundColor: tokens.colorNeutralBackground1,
    fontSize: tokens.fontSizeBase200,
    cursor: "pointer",
    "&:hover": {
      backgroundColor: tokens.colorNeutralBackground1Hover,
    },
  },
  reactionChipMine: {
    border: `1px solid ${tokens.colorBrandStroke1}`,
    backgroundColor: tokens.colorBrandBackground2,
  },
  reactionChipCount: {
    fontSize: tokens.fontSizeBase100,
    color: tokens.colorNeutralForeground2,
  },
  bubbleAttachment: {
    display: "flex",
    alignItems: "center",
    gap: tokens.spacingHorizontalXS,
    marginTop: tokens.spacingVerticalXXS,
    padding: `${tokens.spacingVerticalXXS} ${tokens.spacingHorizontalS}`,
    borderRadius: tokens.borderRadiusSmall,
    backgroundColor: "rgba(255,255,255,0.18)",
    color: "inherit",
    textDecoration: "none",
    fontSize: tokens.fontSizeBase200,
    "&:hover": {
      textDecoration: "underline",
    },
  },
  bubbleDeleted: {
    fontStyle: "italic",
    opacity: 0.7,
  },
  bubbleEdited: {
    fontSize: tokens.fontSizeBase100,
    opacity: 0.7,
    marginLeft: tokens.spacingHorizontalXS,
  },
  composerAttachmentRow: {
    display: "flex",
    alignItems: "center",
    gap: tokens.spacingHorizontalXS,
    padding: `${tokens.spacingVerticalXS} ${tokens.spacingHorizontalM}`,
    borderTop: `1px solid ${tokens.colorNeutralStroke2}`,
    backgroundColor: tokens.colorNeutralBackground2,
    fontSize: tokens.fontSizeBase200,
  },
  composerAttachmentChip: {
    display: "inline-flex",
    alignItems: "center",
    gap: tokens.spacingHorizontalXS,
    padding: `${tokens.spacingVerticalXXS} ${tokens.spacingHorizontalS}`,
    borderRadius: tokens.borderRadiusSmall,
    backgroundColor: tokens.colorNeutralBackground3,
  },
  composerAttachmentDismiss: {
    minWidth: "20px",
    height: "20px",
    padding: "0",
  },
  fileInput: {
    display: "none",
  },
  typingHint: {
    padding: `${tokens.spacingVerticalXXS} ${tokens.spacingHorizontalM}`,
    fontSize: tokens.fontSizeBase200,
    color: tokens.colorNeutralForeground3,
    fontStyle: "italic",
    minHeight: "20px",
  },
  editRow: {
    display: "flex",
    flexDirection: "column",
    gap: tokens.spacingVerticalXXS,
    minWidth: "240px",
  },
  editActions: {
    display: "flex",
    gap: tokens.spacingHorizontalXS,
    justifyContent: "flex-end",
  },
});
